# DIVE INTO CODE COURSE
## Mathematics for Machine Learning Pre-Class assignment 3 Matrix Scratch
### Doan Anh Tien - 1852789 - tien.doan.g0pr0@hcmut.edu.vn

### \[Problem 1] Matrix product is calculated manually
Solve the matrix product of A and B by hand.
Please also explain the calculation process using markdown text.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

In [2]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
print("The matrix A formation: \n{}".format(a_ndarray))
print("\n")
print("The matrix B formation: \n{}".format(b_ndarray))

The matrix A formation: 
[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]


The matrix B formation: 
[[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]


A product of 2 matrixes (also called dot product) is a procedure of multiplying the n-th row values of one matrix with other's n-th column values and take a sum of them to form a new matrix.

For example, the very first value we can get from dot product AB is: taking \[-1 2 3] (row) multiple with \[0 0 2] (column), in which we have

<br><br> <center>$-1 \times 0 + 2 \times 0 + 3 \times 2 = 6$</center>
<br><br>
So in summary, we will have a general calculation which is: $c_{ij} = a_{i1}b_{1j} + a_{i2}b_{2j} + . . . + a_{in}b_{nj} = \sum_{k=1}^n a_{ik}b_{kj}$
for $i = 1,...,m$ and $j = 1,...,p$ and $c_{ij}$ are the values in new matrix C = AB
<br><br>
From there, we will have new value respectively:
<br><br> <center>$c_{12} = 29, c_{13} = -20 $</center>
<br><br> <center>$c_{21} = 12, c_{22} = 52, c_{23} = 38$</center>
<br><br> <center>$c_{21} = -18, c_{22} = -51, c_{23} = -48 $</center>

In [3]:
c_ndarray = np.array([[6,29,-20],[12,52,38],[-18,-51,-48]])
print("The new matrix C formation is: \n{}".format(c_ndarray))

The new matrix C formation is: 
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


### \[Problem 2] Calculation by NumPy function

In [4]:
c_ndarray_np = np.dot(a_ndarray, b_ndarray)
print("The matrix C calculated by np.dot: \n{}".format(c_ndarray_np))

The matrix C calculated by np.dot: 
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


As we can seen that the result by using np.dot function is similar to the hand calculation that we just made from Problem 1.

### \[Problem 3] Implementation of calculation of a certain element

In [5]:
def matrix_multiplication_2x2(array1, array2):
    """
    A function that calculate the product of two matrix (default: 2D) without using the np.matmul, np.dot or @ operator.

    Parameteres:
    --------------
    array1: matrix array
        The array of matrix A
    array2: matrix array
        The array of matrix B

    Returns:
    --------------
    product: int or float
        The dot product of the matrix multiplication

    c_ndarray: matrix array
        The product of the function - matrix C

    """
    product = 0
    c_ndarray = np.zeros(4, int).reshape((2,2))
    for i in range(2):
        for j in range(2):
            for k in range(2):
                c_ndarray[i][j]+=array1[i][k] * array2[k][j]
      
    product = np.sum(c_ndarray)

    return product, c_ndarray

In [6]:
a_ndarray_2x2 = np.array([[1,2],[3,4]])
b_ndarray_2x2 = np.array([[1,2],[3,4]])
product, c_ndarray_2x2 = matrix_multiplication_2x2(a_ndarray_2x2, b_ndarray_2x2)
print("The new matrix: \n{}\n\nThe product value: {}".format(c_ndarray_2x2, product))

The new matrix: 
[[ 7 10]
 [15 22]]

The product value: 54


In [7]:
# Verifying if the function work well
print(np.matmul(a_ndarray_2x2, b_ndarray_2x2))

[[ 7 10]
 [15 22]]


### \[Problem 4] Creating a function that performs matrix multiplication
Since we have properly implement the function in the Problem 3, it just need a small modification for the function to take any matrix as argument (3D, 4D, ...)

In [8]:
def matrix_multiplication(array1, array2):
    """
    A function that calculate the product of two matrix (default: 2D) without using the np.matmul, np.dot or @ operator.

    Parameteres:
    --------------
    array1: matrix array
        The array of matrix A
    array2: matrix array
        The array of matrix B

    Returns:
    --------------
    product: int or float
        The dot product of the matrix multiplication

    c_ndarray: matrix array
        The product of the function - matrix C

    """
    product = 0
    c_ndarray = np.zeros(4, int).reshape((2,2))
    if len(array1) != len(array2[0]):
        print("The dimension is not matched for the multiplication!") # throw out the error if the row of matrix 1
        return 0, []                                                # is unmatch with the column of matrix 2

    for i in range(len(array1)): # I changed this to the length of matrix 1's row for flexible inputting
        for j in range(len(array2[0])): # Iterate the matrix 2's columns
            for k in range(len(array2)): # Iterate the matrix 2's rows
                c_ndarray[i][j]+=array1[i][k] * array2[k][j]
      
    product = np.sum(c_ndarray)

    return product, c_ndarray

In [9]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8], [6, -5], [1, 5]])
product_new, c_ndarray = matrix_multiplication(d_ndarray, e_ndarray)
print("The new matrix: \n{}\n\nThe product value: {}".format(c_ndarray, product_new))

The new matrix: 
[[ 24  -3]
 [-60  87]]

The product value: 48


In [10]:
# Verifying if the function work well
print(np.matmul(d_ndarray, e_ndarray))

[[ 24  -3]
 [-60  87]]


### \[Problem 5] Judge the input whose calculation is not defined

In [11]:
# We will use the matrixes taken from the example of the assignment
d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
product_new, c_ndarray = matrix_multiplication(d_ndarray, e_ndarray)
print("The new matrix: \n{}\n\nThe product value: {}".format(c_ndarray, product_new))

The dimension is not matched for the multiplication!
The new matrix: 
[]

The product value: 0


### \[Problem 6] Transposition

We will use the transposition to solve the error in matrix multiplication.

In [12]:
d_ndarray_ = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]]).T

The new matrix: 
[[ 46  -4]
 [-34  73]]

The product value: 81


What we have here? since we used the transposition function to modify the e_ndarray, it will changed to:
$$\begin{bmatrix} -9 & 6 \\ 8 & -5 \\ 7 & 4 \end{bmatrix}$$

<br> And now we have number of rows in d_ndarray equa to number of columns in e_ndarray. As a result, the matrix product is now defined.


In [14]:
product_new, c_ndarray = matrix_multiplication(d_ndarray, e_ndarray)
print("The new matrix: \n{}\n\nThe product value: {}".format(c_ndarray, product_new))

The new matrix: 
[[ 46  -4]
 [-34  73]]

The product value: 81
