# DIVE INTO CODE COURSE
## Introduction to Machine Learning Pre-class assignment 3 Utilization of Object Orientation
### Doan Anh Tien - 1852789 - tien.doan.g0pr0@hcmut.edu.vn

In [47]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scaler = StandardScaler()
scaler.fit(X)
print("Mean :", scaler.mean_)
print("Variance :", scaler.var_)
X_std = scaler.transform(X)

print(X_std)

Mean : [4.86 3.31 1.45 0.22]
Variance : [0.0764 0.0849 0.0105 0.0056]
[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


### \[Problem 1] Enumeration of classes used so far

In [4]:
import pandas as pd
import matplotlib.pyplot as plt

From the Standardization library, the class is StandardScaler.

Furthermore, there are some classes in pandas like: Series(), DataFrame()

Or in matplotlib: Axes(), Figure()

Or in scikit-learn: LinearRegression(), DecisionTreeRegressor()


### \[Problem 2] Enumeration of methods and instance variables used so far

Methods: load_iris(), fit(), transform(), sum(), isna(), predict()

Instance variables: scaler.mean_, scaler.var_, model.intercept_, x_train.values (values from dataframe), array.shape

In [10]:
X_std = scaler.transform(X)

### \[Problem 3] Creating a standardized class by scratch

In [53]:
class ScratchStandardScaler():
    """
    標準化のためのクラス
    Attributes
    ----------
    mean_ : 次の形のndarray, shape(n_features,)
        平均
    var_ : 次の形のndarray, shape(n_features,)
        分散
    """
    def fit(self, X):
        """
        標準化のために平均と標準偏差を計算する。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            訓練データ
        """
        self.mean_ = sum(X)/len(X)
        self.var_ =  sum((X-self.mean_)**2)/len(X)
        self.mean_ = self.mean_.astype(np.float64, copy=False)
        self.var_ = self.var_.astype(np.float64, copy=False)

    def transform(self, X):
        """
        fitで求めた値を使い標準化を行う。
        Parameters
        ----------
        X : 次の形のndarray, shape (n_samples, n_features)
            特徴量
        Returns
        ----------
        X_scaled : 次の形のndarray, shape (n_samples, n_features)
            標準化された特緒量
        """
        X_scaled = (X - self.mean_)/np.sqrt(self.var_)
        return X_scaled

In [54]:
import numpy as np
from sklearn.datasets import load_iris
data = load_iris()
X = data.data[:10]
scratch_scaler = ScratchStandardScaler()
scratch_scaler.fit(X)
print("Mean : {}".format(scratch_scaler.mean_))
print("Variance : {}\n".format(scratch_scaler.var_))
X_std = scratch_scaler.transform(X)

print(X_std)

Mean : [4.86 3.31 1.45 0.22]
Variance : [0.0764 0.0849 0.0105 0.0056]

[[ 0.86828953  0.65207831 -0.48795004 -0.26726124]
 [ 0.14471492 -1.06391725 -0.48795004 -0.26726124]
 [-0.57885968 -0.37751902 -1.46385011 -0.26726124]
 [-0.94064699 -0.72071813  0.48795004 -0.26726124]
 [ 0.50650222  0.99527742 -0.48795004 -0.26726124]
 [ 1.95365143  2.02487476  2.43975018  2.40535118]
 [-0.94064699  0.3088792  -0.48795004  1.06904497]
 [ 0.50650222  0.3088792   0.48795004 -0.26726124]
 [-1.66422159 -1.40711636 -0.48795004 -0.26726124]
 [ 0.14471492 -0.72071813  0.48795004 -1.60356745]]


Seems like our class build from scratch works pretty well and the results are similar to the Problem 1's output.

In [55]:
class ExampleClass():
    """
    説明用の簡単なクラス
    Parameters
    ----------
    value : float or int
        初期値
    Attributes
    ----------
    value : float or int
        計算結果
    """
    def __init__(self, value):
        self.value = value
        print("初期値{}が設定されました".format(self.value))
    def add(self, value2):
        """
        受け取った引数をself.valueに加える
        """
        self.value += value2
example = ExampleClass(5)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))

初期値5が設定されました
value : 5
value : 8


### \[Problem 4] Creating a class that performs 4 arithmetic operations

In [70]:
class ArithmClass():
    """
    Parameters
    ----------
    value : float or int
    !!! Will raised error if input is string or array
        
    Attributes
    ----------
    value : float or int

    """
    def __init__(self, value):
        try:
            self.value = float(value)
            print("Initial value: {}".format(self.value))
        except ValueError:
            print("Initial value must be a numeric value!")

    def add(self, value2):
        """
        Addtion operators
        """
        self.value += value2

    def sub(self, value2):
        """
        Addtion operators
        """
        self.value -= value2

    def mul(self, value2):
        """
        Addtion operators
        """
        self.value *= value2

    def div(self, value2):
        """
        Addtion operators
        """
        self.value /= value2

example = ArithmClass(12)
print("value : {}".format(example.value))
example.add(3)
print("value : {}".format(example.value))
example.div(5)
print("value : {}".format(example.value))
example.mul(10)
print("value : {}".format(example.value))

Initial value: 12.0
value : 12.0
value : 15.0
value : 3.0
value : 30.0
